#!/bin/bash
FILE="$HOME/.cache/eww.launched"
LOG="/tmp/eww/eww_f5a2b6d0692f81bb.log"
EWW="eww -c $HOME/.config/eww/topbar"

run_eww() {
	if [[ ! $(pidof eww) ]]; then
		${EWW} daemon
		# sleep 5
	fi
	${EWW} open topbar
	${EWW} update mic_volume=$(bash ~/.config/scripts/get-mic-info --volume)
	${EWW} update mic_icon=$(bash ~/.config/scripts/get-mic-info --icon)
	${EWW} update mic_status=$(bash ~/.config/scripts/get-mic-info --status)
	${EWW} update speaker_volume=$(bash ~/.config/scripts/get-speaker-info --volume)
	${EWW} update speaker_icon=$(bash ~/.config/scripts/get-speaker-info --icon)
	${EWW} update speaker_status=$(bash ~/.config/scripts/get-speaker-info --status)
	${EWW} update brightness_value=$(bash ~/.config/scripts/get-brightness-info --value)
	${EWW} update brightness_icon=$(bash ~/.config/scripts/get-brightness-info --icon)
}

if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww
elif [[ "$1" = "-f" && "$2" = "start" ]]; then
	${EWW} close-all && killall eww
	rm "$FILE"
	touch "$FILE"
	run_eww
else
	${EWW} close-all && killall eww
	rm "$FILE"
fi

# sleep 1
rm "$LOG"
