#!/bin/bash
FILE="$HOME/.cache/eww.launched"
EWW="eww -c $HOME/.config/eww/topbar"

run_eww() {
	if [[ ! $(pidof eww) ]]; then
		${EWW} daemon
	fi
	${EWW} open topbar
	${EWW} update mic_volume=$(bash ~/.local/share/scripts/system/get-mic-info --volume)
	${EWW} update mic_icon=$(bash ~/.local/share/scripts/system/get-mic-info --icon)
	${EWW} update mic_status=$(bash ~/.local/share/scripts/system/get-mic-info --status)
	${EWW} update speaker_volume=$(bash ~/.local/share/scripts/system/get-speaker-info --volume)
	${EWW} update speaker_icon=$(bash ~/.local/share/scripts/system/get-speaker-info --icon)
	${EWW} update speaker_status=$(bash ~/.local/share/scripts/system/get-speaker-info --status)
	${EWW} update brightness_value=$(bash ~/.local/share/scripts/system/get-brightness-info --value)
	${EWW} update brightness_icon=$(bash ~/.local/share/scripts/system/get-brightness-info --icon)
}

if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww
elif [[ "$1" = "-f" && "$2" = "start" ]]; then
	${EWW} close-all && killall eww
	rm "$FILE"
	touch "$FILE"
	run_eww
else
	${EWW} close-all && killall eww
	rm "$FILE"
fi

rm /tmp/eww/eww*.log
