#! /bin/bash
EWW="eww -c $HOME/.config/eww/topbar"
if [[ "$1" = "-i" ]]; then
    pamixer --source 1 -i "$2"
elif [[ "$1" = "-d" ]]; then
    pamixer --source 1 -d "$2"
elif [[ "$1" = "-t" ]]; then
    pamixer --source 1 -t
elif [[ "$1" = "-s" ]]; then
    pamixer --source 1 --set-volume "$2"
fi
${EWW} update mic_volume="$(bash ~/.config/scripts/get-mic-info --volume)"
${EWW} update mic_icon="$(bash ~/.config/scripts/get-mic-info --icon)"
${EWW} update mic_status="$(bash ~/.config/scripts/get-mic-info --status)"
