#! /bin/bash
function clamp {
    min=$1
    max=$2
    val=$3
    if [[ $val -lt $min ]]; then
        echo "$max"
    elif [[ $val -gt $max ]]; then
        echo "$min"
    else
        echo "$val"
    fi
}

direction=$1
current=$2
if test "$direction" = "down"
then
    target=$(clamp 1 5 $((current+1)))
    hyprctl dispatch workspace "$target"
elif test "$direction" = "up"
then
    target=$(clamp 1 5 $((current-1)))
    hyprctl dispatch workspace "$target"
fi
