#! /bin/bash
volume=$(pamixer --source 1 --get-volume-human | tr -d '%')
if [[ "$volume" = "muted" ]]; then
    volume=0;
    status="muted"
else
    status="normal"
fi

if [[ "$1" = "--volume" ]]; then
    echo "$volume"
elif [[ "$1" = "--status" ]]; then
    echo $status
elif [[ "$1" = "--icon" ]]; then
    if [[ $volume -eq 0 ]]; then
        echo "󰍭"
    else
        echo "󰍬"
    fi
fi
