#!/bin/bash
LOCK_FILE="$HOME/.cache/eww-calendar.lock"
EWW="eww -c $HOME/.config/eww/topbar"

if [[ ! -f "$LOCK_FILE" ]]; then
    touch "$LOCK_FILE"
    ${EWW} open calendarbar
elif [[ -f "$LOCK_FILE" ]]; then
    rm "$LOCK_FILE"
    ${EWW} close calendarbar
fi
