cursor #c0caf5
cursor_text_color #a9b1d6

foreground            #c0caf5
background            #24283b
selection_foreground  #24283b
selection_background  #bb9af7
url_color             #7aa2f7

color0   #24283b
color1   #8c0c0b
color2   #0a7209
color3   #7f7511
color4   #5490ff
color5   #3e6ed1
color6   #7aa2f7
color7   #1a1a1a
color8   #2e2e2e
color9   #a52120
color10  #148c13
color11  #998e21
color12  #719eff
color13  #3f9dff
color14  #7559ff
color15  #1a1a1a
